### ISSUE TITLE
check out photopea/UNN.js

### ISSUE THREAD

**Issue by leeoniya** [fabiospampinato/toygrad#1]
@fabiospampinato 

https://github.com/photopea/UNN.js

could be useful, maybe.

**Comment by fabiospampinato** [comment]
Thanks for the pointer 👍 It seems more geared toward convolutions, I haven't gotten that far yeah 🤣

**Comment by fabiospampinato** [comment]
The kind of upstream ConvNetJS seems much more readable https://github.com/karpathy/convnetjs

I think I'll try to do something like that so that convolutions are available also. It seems tricky though, I don't entirely understand how it works 🤔

**Comment by leeoniya** [comment]
i'm currently searching for RNN/LSTM to do timeseries anomaly detection and https://github.com/karpathy/recurrentjs seems to be the most terse / dependency-free :)

this isn't terribly encouraging :grimacing: https://github.com/karpathy/recurrentjs#warning-beta

not sure how close i can get to this: https://www.renom.jp/notebooks/tutorial/time_series/lstm-anomalydetection/notebook.html

**Comment by fabiospampinato** [comment]
Getting these models trained in JS is playing in hard mode 🤣

I might get to RRNs/LSTMs, I'm kind of exploring the field at the moment, I'd like to know more about this stuff, but I don't need those immediately myself.

If Grafana would like to sponsor some development maybe I can consider focusing on that shortly/until it's done.

**Comment by leeoniya** [comment]
> If Grafana would like to sponsor some development maybe I can consider focusing on that shortly/until it's done.

ha, for sure not in JS. we have a whole ML division, and you can bet they're leaning heavily into the existing Python-centric ecosystem. it all has to play nice with alerting and live data ingestion at scale, so it's all Go & Python->C.

we have a bit of frontend code that does MAD or 1D dbscan for fast feedback while tweaking detection params, but i'm just toying around with stuff on my own to make a cool extra demo for https://leeoniya.github.io/uPlot/demos/data-smoothing.html
